import CtaButton from "@/app/components/buttons/ctaButton";
import Image from "next/image";
import Link from "next/link";

export function ForInvestorsComponent() {
  return (
    <>
      <div className="w-[50vw] hidden sm:block absolute right-0 top-[0px]">
        <CtaButton
          className="custom-font-4 ml-[21vw] mt-[12vh] text-2xl"
          onClick={() => {
            window.open("https://github.com/TsotneDarjania/football-manager");
          }}
          label="Open Codebase"
        />
        <CtaButton
          className="custom-font-4 ml-[21vw] mt-[12vh] text-2xl"
          onClick={() => {
            window.open("https://www.youtube.com/@Marb1eArena");
          }}
          label="Open Youtube Channel"
        />
        {/* Image 1 */}
        <div
          className={
            "w-[36vw] min-h-[260px] grayscale-[100%] relative ml-[10vw] mt-[85vh] shadow"
          }
        >
          <Image
            fill
            src="/website/images/pageAssets/image-5.png"
            sizes="100vw"
            alt="youtube-icon"
          />
        </div>
      </div>

      {/* Text */}
      <div className="ml-2 text-xl w-[90vw] sm:w-[50vw] mt-[80px] text-[#68c0bc] custom-font-4 pb-11">
        <p>
          This text is not generated by AI, so you can read it carefully.{" "}
          <br></br> <br></br>If you have the vision to see the future potential
          of this game in the browser gaming industry and the resources to
          invest, I invite you to contact me to discuss future plans for this
          project.
        </p>
        <div className="sm:hidden pb-4">
          <CtaButton
            className="custom-font-4 mt-[12vh] text-2xl"
            onClick={() => {
              window.open("https://www.youtube.com/@Marb1eArena");
            }}
            label="Open Youtube Channel"
          />
        </div>
        <h2 className="text-[#cdf7f4] custom-font-4 font-bold text-2xl mt-[50px] underline">
          <Link
            target="_blank"
            className="text-[#cdf7f4] custom-font-4 font-bold text-2xl mt-[50px] underline"
            href={
              "https://www.linkedin.com/pulse/browser-games-market-report-global-demand-insights-7mlvf/"
            }
          >
            {" "}
            browser games industry
          </Link>{" "}
        </h2>
        <p>
          To provide some context, recent statistics from reputable sources like
          Newzoo and Statista show a significant rise in the popularity of
          browser games. The global market for browser games is expected to
          reach a value of over $10 billion by 2025, representing substantial
          growth opportunities. Within this market, sports and strategy games
          have demonstrated particularly strong performance, attracting a
          diverse and engaged player base.
          <br></br>
          <br></br>
          For example, data reveals that the sports gaming segment alone is
          projected to account for a significant share of the browser games
          market, with a compound annual growth rate (CAGR) exceeding 8% over
          the next few years. Similarly, strategy games continue to enjoy robust
          growth, fueled by increasing demand from both casual and hardcore
          gamers.
        </p>
        <h2 className="text-[#cdf7f4] custom-font-4 font-bold text-2xl mt-[50px] underline">
          For Contributors
        </h2>
        <p>
          <br></br> Are you a passionate JavaScript developer looking to create
          something truly unique and exciting? Do you value open-source projects
          over large, closed corporations? If so, this project is for you. By
          joining, you will have the opportunity to enhance your coding skills
          and gain valuable experience. You will be able to express your
          creativity and help steer the project in the direction you believe is
          best. Plus, long-term collaborators will receive financial benefits if
          the project succeeds.
        </p>
        <div className="sm:hidden pb-4">
          <CtaButton
            className="custom-font-4 mt-[12vh] text-2xl"
            onClick={() => {
              window.open("https://github.com/TsotneDarjania/football-manager");
            }}
            label="Open Codebase"
          />
        </div>
        <h2 className="text-[#cdf7f4] custom-font-4 font-bold text-2xl mt-[50px] underline">
          Contact Information
        </h2>
        <p className="custom-font-2 mt-4 text-lg sm:text-sm">
          Email : tsotnedarjania1997@gmail.com
        </p>
        <p className="custom-font-2 mt-4 text-lg sm:text-sm">
          Phone : +995 592 02 28 24
        </p>

        <p className="custom-font-2 mt-4 text-lg sm:text-sm">
          LinkedIn :{" "}
          <Link
            target="_blank"
            className="font-bold text-blue-500 h-[20vh] underline text-xl cursor-pointer"
            href={"https://www.linkedin.com/in/tsotne-darjania-58380b231/"}
          >
            {" "}
            Tsotne Darjania
          </Link>
        </p>
      </div>
    </>
  );
}
